-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 12:22:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema YouTube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `YouTube` ;

-- -----------------------------------------------------
-- Schema YouTube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `YouTube` DEFAULT CHARACTER SET utf8 ;
USE `YouTube` ;

-- -----------------------------------------------------
-- Table `YouTube`.`Canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YouTube`.`Canal` (
  `idCanal` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha creacion` DATE NOT NULL,
  PRIMARY KEY (`idCanal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YouTube`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YouTube`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(10) NULL,
  `pais` VARCHAR(45) NULL,
  `fecha nacimiento` DATE NOT NULL,
  `codigo postal` INT NULL,
  `Canal_idCanal` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Usuario_Canal1`
    FOREIGN KEY (`Canal_idCanal`)
    REFERENCES `YouTube`.`Canal` (`idCanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Canal1_idx` ON `YouTube`.`Usuario` (`Canal_idCanal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `YouTube`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YouTube`.`Video` (
  `idVideo` INT NOT NULL,
  `titulo` VARCHAR(85) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `nombre del archivo` VARCHAR(45) NOT NULL,
  `duracion` INT NOT NULL,
  `thumbnail` VARCHAR(45) NOT NULL,
  `reproducciones` INT NOT NULL,
  `tamaño` INT NOT NULL,
  `tipo video` ENUM('publico', 'privado', 'oculto') NOT NULL,
  `Canal_idCanal` INT NOT NULL,
  PRIMARY KEY (`idVideo`),
  CONSTRAINT `fk_Video_Canal1`
    FOREIGN KEY (`Canal_idCanal`)
    REFERENCES `YouTube`.`Canal` (`idCanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Video_Canal1_idx` ON `YouTube`.`Video` (`Canal_idCanal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `YouTube`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YouTube`.`Comentario` (
  `idComentario` INT NOT NULL,
  `texto` VARCHAR(250) NOT NULL,
  `fecha-hora` DATETIME(1) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `YouTube`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Comentario_Usuario1_idx` ON `YouTube`.`Comentario` (`Usuario_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `YouTube`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YouTube`.`playlist` (
  `idplaylist` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `tipo` ENUM('privada', 'publica') NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idplaylist`),
  CONSTRAINT `fk_playlist_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `YouTube`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_playlist_Usuario1_idx` ON `YouTube`.`playlist` (`Usuario_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `YouTube`.`Etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YouTube`.`Etiqueta` (
  `idEtiqueta` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Video_idVideo` INT NOT NULL,
  PRIMARY KEY (`idEtiqueta`),
  CONSTRAINT `fk_Etiqueta_Video`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `YouTube`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Etiqueta_Video_idx` ON `YouTube`.`Etiqueta` (`Video_idVideo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `YouTube`.`like_dislike`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YouTube`.`like_dislike` (
  `idlike_dislike` INT NOT NULL,
  `fecha-hora` DATETIME(1) NOT NULL,
  `tipo` ENUM('like', 'dislike') NOT NULL,
  `Video_idVideo` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Comentario_idComentario` INT NOT NULL,
  PRIMARY KEY (`idlike_dislike`),
  CONSTRAINT `fk_like_dislike_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `YouTube`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_dislike_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `YouTube`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_dislike_Comentario1`
    FOREIGN KEY (`Comentario_idComentario`)
    REFERENCES `YouTube`.`Comentario` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_like_dislike_Video1_idx` ON `YouTube`.`like_dislike` (`Video_idVideo` ASC) VISIBLE;

CREATE INDEX `fk_like_dislike_Usuario1_idx` ON `YouTube`.`like_dislike` (`Usuario_idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_like_dislike_Comentario1_idx` ON `YouTube`.`like_dislike` (`Comentario_idComentario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `YouTube`.`Subscripción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YouTube`.`Subscripción` (
  `idSubscripción` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Canal_idCanal` INT NOT NULL,
  PRIMARY KEY (`idSubscripción`),
  CONSTRAINT `fk_Subscripción_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `YouTube`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscripción_Canal1`
    FOREIGN KEY (`Canal_idCanal`)
    REFERENCES `YouTube`.`Canal` (`idCanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Subscripción_Usuario1_idx` ON `YouTube`.`Subscripción` (`Usuario_idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Subscripción_Canal1_idx` ON `YouTube`.`Subscripción` (`Canal_idCanal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `YouTube`.`playlist_has_Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YouTube`.`playlist_has_Video` (
  `playlist_idplaylist` INT NOT NULL,
  `Video_idVideo` INT NOT NULL,
  PRIMARY KEY (`playlist_idplaylist`, `Video_idVideo`),
  CONSTRAINT `fk_playlist_has_Video_playlist1`
    FOREIGN KEY (`playlist_idplaylist`)
    REFERENCES `YouTube`.`playlist` (`idplaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_has_Video_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `YouTube`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_playlist_has_Video_Video1_idx` ON `YouTube`.`playlist_has_Video` (`Video_idVideo` ASC) VISIBLE;

CREATE INDEX `fk_playlist_has_Video_playlist1_idx` ON `YouTube`.`playlist_has_Video` (`playlist_idplaylist` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
