-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 13:35:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Spotify` ;

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotify` DEFAULT CHARACTER SET utf8 ;
USE `Spotify` ;

-- -----------------------------------------------------
-- Table `Spotify`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigo postal` INT(12) NOT NULL,
  `fecha nacimiento` DATE NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Subscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Subscripcion` (
  `idSubscripcion` INT NOT NULL,
  `fecha inicio` DATE NOT NULL,
  `renovacion` DATE NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idSubscripcion`),
  CONSTRAINT `fk_Subscripcion_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Subscripcion_Usuario1_idx` ON `Spotify`.`Subscripcion` (`Usuario_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Tarjeta` (
  `idTarjeta` INT NOT NULL,
  `numero tarjeta` INT NOT NULL,
  `fecha caducidad` INT NOT NULL,
  `CV` INT(5) NOT NULL,
  PRIMARY KEY (`idTarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Paypal` (
  `idPaypal` INT NOT NULL,
  `nombre usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaypal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Pago` (
  `idPago` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `total` FLOAT NOT NULL,
  `Subscripcion_idSubscripcion` INT NOT NULL,
  `Paypal_idPaypal` INT NOT NULL,
  `Tarjeta_idTarjeta` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  CONSTRAINT `fk_Pago_Subscripcion1`
    FOREIGN KEY (`Subscripcion_idSubscripcion`)
    REFERENCES `Spotify`.`Subscripcion` (`idSubscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_Paypal1`
    FOREIGN KEY (`Paypal_idPaypal`)
    REFERENCES `Spotify`.`Paypal` (`idPaypal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_Tarjeta1`
    FOREIGN KEY (`Tarjeta_idTarjeta`)
    REFERENCES `Spotify`.`Tarjeta` (`idTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pago_Subscripcion1_idx` ON `Spotify`.`Pago` (`Subscripcion_idSubscripcion` ASC) VISIBLE;

CREATE INDEX `fk_Pago_Paypal1_idx` ON `Spotify`.`Pago` (`Paypal_idPaypal` ASC) VISIBLE;

CREATE INDEX `fk_Pago_Tarjeta1_idx` ON `Spotify`.`Pago` (`Tarjeta_idTarjeta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Playlists` (
  `idPlaylists` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `cancion` VARCHAR(45) NOT NULL,
  `fecha creacion` DATE NOT NULL,
  PRIMARY KEY (`idPlaylists`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Genero musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Genero musical` (
  `idGenero musical` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero musical`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Artista` (
  `idArtista` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen artista` VARCHAR(45) NOT NULL,
  `Genero musical_idGenero musical` INT NOT NULL,
  PRIMARY KEY (`idArtista`),
  CONSTRAINT `fk_Artista_Genero musical1`
    FOREIGN KEY (`Genero musical_idGenero musical`)
    REFERENCES `Spotify`.`Genero musical` (`idGenero musical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Artista_Genero musical1_idx` ON `Spotify`.`Artista` (`Genero musical_idGenero musical` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Album` (
  `idAlbum` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `año publicacion` INT(5) NOT NULL,
  `imagen portada` VARCHAR(45) NOT NULL,
  `Artista_idArtista` INT NOT NULL,
  PRIMARY KEY (`idAlbum`),
  CONSTRAINT `fk_Album_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `Spotify`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Album_Artista1_idx` ON `Spotify`.`Album` (`Artista_idArtista` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Cancion` (
  `idCancion` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `duracion` FLOAT NOT NULL,
  `numero reproduciones` INT NOT NULL,
  `Album_idAlbum` INT NOT NULL,
  PRIMARY KEY (`idCancion`, `Album_idAlbum`),
  CONSTRAINT `fk_Cancion_Album1`
    FOREIGN KEY (`Album_idAlbum`)
    REFERENCES `Spotify`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cancion_Album1_idx` ON `Spotify`.`Cancion` (`Album_idAlbum` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlists_has_Cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Playlists_has_Cancion` (
  `Playlists_idPlaylists` INT NOT NULL,
  `Cancion_idCancion` INT NOT NULL,
  PRIMARY KEY (`Playlists_idPlaylists`, `Cancion_idCancion`),
  CONSTRAINT `fk_Playlists_has_Cancion_Playlists1`
    FOREIGN KEY (`Playlists_idPlaylists`)
    REFERENCES `Spotify`.`Playlists` (`idPlaylists`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlists_has_Cancion_Cancion1`
    FOREIGN KEY (`Cancion_idCancion`)
    REFERENCES `Spotify`.`Cancion` (`idCancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Playlists_has_Cancion_Cancion1_idx` ON `Spotify`.`Playlists_has_Cancion` (`Cancion_idCancion` ASC) VISIBLE;

CREATE INDEX `fk_Playlists_has_Cancion_Playlists1_idx` ON `Spotify`.`Playlists_has_Cancion` (`Playlists_idPlaylists` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Cancion favorita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Cancion favorita` (
  `idCancion favorita` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Cancion_idCancion` INT NOT NULL,
  `Cancion_Album_idAlbum` INT NOT NULL,
  PRIMARY KEY (`idCancion favorita`),
  CONSTRAINT `fk_Cancion favorita_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cancion favorita_Cancion1`
    FOREIGN KEY (`Cancion_idCancion` , `Cancion_Album_idAlbum`)
    REFERENCES `Spotify`.`Cancion` (`idCancion` , `Album_idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cancion favorita_Usuario1_idx` ON `Spotify`.`Cancion favorita` (`Usuario_idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Cancion favorita_Cancion1_idx` ON `Spotify`.`Cancion favorita` (`Cancion_idCancion` ASC, `Cancion_Album_idAlbum` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Album favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Album favorito` (
  `idAlbum favorito` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Album_idAlbum` INT NOT NULL,
  PRIMARY KEY (`idAlbum favorito`),
  CONSTRAINT `fk_Album favorito_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Album favorito_Album1`
    FOREIGN KEY (`Album_idAlbum`)
    REFERENCES `Spotify`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Album favorito_Usuario1_idx` ON `Spotify`.`Album favorito` (`Usuario_idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Album favorito_Album1_idx` ON `Spotify`.`Album favorito` (`Album_idAlbum` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Artista favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Artista favorito` (
  `idArtista favorito` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Artista_idArtista` INT NOT NULL,
  PRIMARY KEY (`idArtista favorito`),
  CONSTRAINT `fk_Artista favorito_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artista favorito_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `Spotify`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Artista favorito_Usuario1_idx` ON `Spotify`.`Artista favorito` (`Usuario_idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Artista favorito_Artista1_idx` ON `Spotify`.`Artista favorito` (`Artista_idArtista` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlist eliminada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Playlist eliminada` (
  `idPlaylist eliminada` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `Playlists_idPlaylists` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPlaylist eliminada`),
  CONSTRAINT `fk_Playlist eliminada_Playlists1`
    FOREIGN KEY (`Playlists_idPlaylists`)
    REFERENCES `Spotify`.`Playlists` (`idPlaylists`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist eliminada_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Playlist eliminada_Playlists1_idx` ON `Spotify`.`Playlist eliminada` (`Playlists_idPlaylists` ASC) VISIBLE;

CREATE INDEX `fk_Playlist eliminada_Usuario1_idx` ON `Spotify`.`Playlist eliminada` (`Usuario_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlists_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Playlists_has_Usuario` (
  `Playlists_idPlaylists` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Playlists_idPlaylists`, `Usuario_idUsuario`),
  CONSTRAINT `fk_Playlists_has_Usuario_Playlists1`
    FOREIGN KEY (`Playlists_idPlaylists`)
    REFERENCES `Spotify`.`Playlists` (`idPlaylists`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlists_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Playlists_has_Usuario_Usuario1_idx` ON `Spotify`.`Playlists_has_Usuario` (`Usuario_idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Playlists_has_Usuario_Playlists1_idx` ON `Spotify`.`Playlists_has_Usuario` (`Playlists_idPlaylists` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
