-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 14:02:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema culo_botella
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `culo_botella` ;

-- -----------------------------------------------------
-- Schema culo_botella
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culo_botella` DEFAULT CHARACTER SET utf8 ;
USE `culo_botella` ;

-- -----------------------------------------------------
-- Table `culo_botella`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culo_botella`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(90) NOT NULL,
  `Direccion` VARCHAR(120) NOT NULL,
  `Telefono` INT(12) NOT NULL,
  `Fax` VARCHAR(15) NOT NULL,
  `Nif` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culo_botella`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culo_botella`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idMarca`),
  CONSTRAINT `fk_Marca_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `culo_botella`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Marca_Proveedor1_idx` ON `culo_botella`.`Marca` (`Proveedor_idProveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `culo_botella`.`Gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culo_botella`.`Gafas` (
  `idGlasses` INT NOT NULL AUTO_INCREMENT,
  `Graduacion derecha` FLOAT(5) ZEROFILL NULL,
  `Graduacion izquierda` FLOAT(5) ZEROFILL NULL,
  `Tipo montura` VARCHAR(45) NOT NULL,
  `Color montura` VARCHAR(45) NOT NULL,
  `Color vidrio derecho` VARCHAR(15) NOT NULL,
  `Color vidrio izquierdo` VARCHAR(15) NOT NULL,
  `precio` FLOAT(10) NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  CONSTRAINT `fk_Gafas_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `culo_botella`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Gafas_Marca1_idx` ON `culo_botella`.`Gafas` (`Marca_idMarca` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `culo_botella`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culo_botella`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(90) NOT NULL,
  `Direccion` VARCHAR(120) NOT NULL,
  `Telefono` INT(12) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Fecha registro` DATE NOT NULL,
  `Recomendador_IdCliente` INT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_Cliente_Cliente1`
    FOREIGN KEY (`Recomendador_IdCliente`)
    REFERENCES `culo_botella`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_Cliente1_idx` ON `culo_botella`.`Cliente` (`Recomendador_IdCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `culo_botella`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culo_botella`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `Nombre` VARCHAR(90) NOT NULL,
  `Direccion` VARCHAR(120) NOT NULL,
  `Telefono` INT(12) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culo_botella`.`Venta/Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `culo_botella`.`Venta/Compra` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Gafas_idGlasses` INT NOT NULL,
  `Nombre Cliente` VARCHAR(45) NOT NULL,
  `Nombre Empleado` VARCHAR(45) NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  CONSTRAINT `fk_Venta_Gafas1`
    FOREIGN KEY (`Gafas_idGlasses`)
    REFERENCES `culo_botella`.`Gafas` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta/Compra_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `culo_botella`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta/Compra_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `culo_botella`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Venta_Gafas1_idx` ON `culo_botella`.`Venta/Compra` (`Gafas_idGlasses` ASC) VISIBLE;

CREATE INDEX `fk_Venta/Compra_Empleado1_idx` ON `culo_botella`.`Venta/Compra` (`Empleado_idEmpleado` ASC) VISIBLE;

CREATE INDEX `fk_Venta/Compra_Cliente1_idx` ON `culo_botella`.`Venta/Compra` (`Cliente_idCliente` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
