-- MySQL Script generated by MySQL Workbench
-- Wed Apr 12 09:16:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `Codigo postal` INT(9) NOT NULL,
  `Provincia_idProvincia` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  CONSTRAINT `fk_Municipio_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `mydb`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Municipio_Provincia1_idx` ON `mydb`.`Municipio` (`Provincia_idProvincia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` INT(12) NOT NULL,
  `Municipio_idMunicipio` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_Cliente_Municipio1`
    FOREIGN KEY (`Municipio_idMunicipio`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_Municipio1_idx` ON `mydb`.`Cliente` (`Municipio_idMunicipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tienda` (
  `idTienda` INT NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Municipio_idMunicipio` INT NOT NULL,
  PRIMARY KEY (`idTienda`),
  CONSTRAINT `fk_Tienda_Municipio1`
    FOREIGN KEY (`Municipio_idMunicipio`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tienda_Municipio1_idx` ON `mydb`.`Tienda` (`Municipio_idMunicipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `NIF` INT(12) NOT NULL,
  `Telefono` INT(12) NOT NULL,
  `Puesto` VARCHAR(45) NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  CONSTRAINT `fk_Empleado_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Empleado_Tienda1_idx` ON `mydb`.`Empleado` (`Tienda_idTienda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comanda` (
  `idComanda` INT NOT NULL AUTO_INCREMENT,
  `Tipo comanda` VARCHAR(45) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio total` FLOAT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idComanda`),
  CONSTRAINT `fk_Comanda_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comanda_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comanda_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Comanda_Empleado1_idx` ON `mydb`.`Comanda` (`Empleado_idEmpleado` ASC) VISIBLE;

CREATE INDEX `fk_Comanda_Tienda1_idx` ON `mydb`.`Comanda` (`Tienda_idTienda` ASC) VISIBLE;

CREATE INDEX `fk_Comanda_Cliente1_idx` ON `mydb`.`Comanda` (`Cliente_idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria pizza` (
  `idCategoria pizza` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hamburguesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hamburguesa` (
  `idHamburguesa` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(60) NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Precio` INT NOT NULL,
  `Comanda_idComanda` INT NOT NULL,
  PRIMARY KEY (`idHamburguesa`),
  CONSTRAINT `fk_Hamburguesa_Comanda1`
    FOREIGN KEY (`Comanda_idComanda`)
    REFERENCES `mydb`.`Comanda` (`idComanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Hamburguesa_Comanda1_idx` ON `mydb`.`Hamburguesa` (`Comanda_idComanda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bebidas` (
  `idBebidas` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(60) NOT NULL,
  `Imagen` VARCHAR(45) NULL,
  `Precio` INT NOT NULL,
  `Comanda_idComanda` INT NOT NULL,
  PRIMARY KEY (`idBebidas`),
  CONSTRAINT `fk_Bebidas_Comanda1`
    FOREIGN KEY (`Comanda_idComanda`)
    REFERENCES `mydb`.`Comanda` (`idComanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Bebidas_Comanda1_idx` ON `mydb`.`Bebidas` (`Comanda_idComanda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizza` (
  `idHamburguesa` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(60) NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Precio` INT NOT NULL,
  `Categoria pizza_idCategoria pizza` INT NOT NULL,
  `Comanda_idComanda` INT NOT NULL,
  PRIMARY KEY (`idHamburguesa`),
  CONSTRAINT `fk_Pizza_Categoria pizza1`
    FOREIGN KEY (`Categoria pizza_idCategoria pizza`)
    REFERENCES `mydb`.`Categoria pizza` (`idCategoria pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_Comanda1`
    FOREIGN KEY (`Comanda_idComanda`)
    REFERENCES `mydb`.`Comanda` (`idComanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pizza_Categoria pizza1_idx` ON `mydb`.`Pizza` (`Categoria pizza_idCategoria pizza` ASC) VISIBLE;

CREATE INDEX `fk_Pizza_Comanda1_idx` ON `mydb`.`Pizza` (`Comanda_idComanda` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
